// COMPLETE MARKETPLACE DATABASE - ALL CATEGORIES WITH 25+ BUSINESSES
// This adds Salons, Laundry, Electronics, and Fashion to complete the marketplace

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Listing from '../models/Listing.js';
import User from '../models/User.js';

dotenv.config();

const completeBusinessData = [
    // ============ SALONS & BARBERS (27 businesses) ============
    {
        name: 'Akhter Ali Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Dhanmondi' },
        shortDescription: 'Legendary barber since 1972',
        description: 'Iconic Dhaka salon known for classic cuts and modern styles. Expert in both traditional and contemporary hairstyling.',
        phone: '+880 1711-111001',
        hours: '9 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400',
        externalBookingUrl: null,
        rating: 4.8,
        reviewCount: 1234,
        popularity: 4500,
    },
    {
        name: 'Persona The Ultimate Makeover',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'Premium unisex salon & spa',
        description: 'High-end salon offering haircuts, coloring, spa treatments, and bridal packages. International trained stylists.',
        phone: '+880 1722-111002',
        hours: '10 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.9,
        reviewCount: 2100,
        popularity: 6200,
    },
    {
        name: 'Gents & Ladies Parlour',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Mirpur' },
        shortDescription: 'Affordable family salon',
        description: 'Popular neighborhood salon for men, women, and children. Quality service at budget-friendly prices.',
        phone: '+880 1733-111003',
        hours: '9 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
        externalBookingUrl: null,
        rating: 4.5,
        reviewCount: 678,
        popularity: 2800,
    },
    {
        name: 'Farzana Shakil\'s Makeover Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Banani' },
        shortDescription: 'Celebrity makeup artist salon',
        description: 'Renowned for bridal makeup and hairstyling. Premium services with celebrity clientele.',
        phone: '+880 1744-111004',
        hours: '11 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=400',
        externalBookingUrl: null,
        rating: 4.9,
        reviewCount: 1567,
        popularity: 5400,
    },
    {
        name: 'The Cut Barber Shop',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Uttara' },
        shortDescription: 'Modern men\'s grooming',
        description: 'Specialized men\'s salon with beard sculpting, hot towel shaves, and modern haircuts.',
        phone: '+880 1755-111005',
        hours: '10 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 892,
        popularity: 3600,
    },
    {
        name: 'Toni&Guy Dhaka',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'International salon chain',
        description: 'British hairdressing brand with cutting-edge styles and professional color services.',
        phone: '+880 1766-111006',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.8,
        reviewCount: 1345,
        popularity: 4900,
    },
    {
        name: 'Monsoon Salon & Spa',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Dhanmondi' },
        shortDescription: 'Full-service beauty center',
        description: 'Complete salon and spa with Thai massage, facials, hair treatments, and nail services.',
        phone: '+880 1777-111007',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=400',
        externalBookingUrl: null,
        rating: 4.6,
        reviewCount: 734,
        popularity: 3200,
    },
    {
        name: 'Scissors Unisex Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Bashundhara' },
        shortDescription: 'Mall-based modern salon',
        description: 'Convenient mall location with walk-in service. Haircuts, styling, and basic treatments.',
        phone: '+880 1788-111008',
        hours: '11 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
        externalBookingUrl: null,
        rating: 4.4,
        reviewCount: 456,
        popularity: 2100,
    },
    {
        name: 'Depilex Beauty Clinic',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'Premium beauty & wellness',
        description: 'Luxury beauty clinic offering advanced hair, skin, and body treatments.',
        phone: '+880 1799-111009',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400',
        externalBookingUrl: null,
        rating: 4.8,
        reviewCount: 1123,
        popularity: 4200,
    },
    {
        name: 'Banglar Chul (Men\'s Salon)',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Mirpur' },
        shortDescription: 'Local favorite barber shop',
        description: 'Traditional barber with modern touches. Known for precision cuts and friendly service.',
        phone: '+880 1700-111010',
        hours: '9 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400',
        externalBookingUrl: null,
        rating: 4.5,
        reviewCount: 567,
        popularity: 2400,
    },
    {
        name: 'Jawed Habib Hair & Beauty',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Banani' },
        shortDescription: 'Indian salon chain',
        description: 'Famous Indian hairstylist brand. Offers haircuts, coloring, and hair spa treatments.',
        phone: '+880 1811-111011',
        hours: '10 AM - 8:30 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.6,
        reviewCount: 823,
        popularity: 3500,
    },
    {
        name: 'Looks Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Dhanmondi' },
        shortDescription: 'Trendy styling hub',
        description: 'Fashion-forward salon specializing in contemporary styles and hair color trends.',
        phone: '+880 1822-111012',
        hours: '11 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 698,
        popularity: 3100,
    },
    {
        name: 'Hair Studio 71',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Uttara' },
        shortDescription: 'Professional hair care center',
        description: 'Specialized in hair treatments, keratin therapy, and rebonding services.',
        phone: '+880 1833-111013',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.5,
        reviewCount: 445,
        popularity: 1900,
    },
    {
        name: 'Elegance Beauty Parlour',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'Ladies exclusive salon',
        description: 'Women-only salon with privacy. Bridal packages, party makeup, and hair services.',
        phone: '+880 1844-111014',
        hours: '10 AM - 7 PM',
        imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=400',
        externalBookingUrl: null,
        rating: 4.6,
        reviewCount: 567,
        popularity: 2600,
    },
    {
        name: 'Grafting Hair Studio',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Banani' },
        shortDescription: 'Hair transplant & styling',
        description: 'Advanced hair clinic offering transplants, treatments, and styling services.',
        phone: '+880 1855-111015',
        hours: '9 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 892,
        popularity: 3400,
    },
    {
        name: 'Shampoo Lounge',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Bashundhara' },
        shortDescription: 'Quick service salon',
        description: 'Express salon for busy professionals. Quality cuts in minimal time.',
        phone: '+880 1866-111016',
        hours: '10 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
        externalBookingUrl: null,
        rating: 4.4,
        reviewCount: 389,
        popularity: 1700,
    },
    {
        name: 'Naturals Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Uttara' },
        shortDescription: 'Natural beauty products salon',
        description: 'Uses organic and natural products. Eco-friendly salon with quality services.',
        phone: '+880 1877-111017',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=400',
        externalBookingUrl: null,
        rating: 4.5,
        reviewCount: 512,
        popularity: 2200,
    },
    {
        name: 'Styling Zone',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Mirpur' },
        shortDescription: 'Affordable family cuts',
        description: 'Budget-friendly salon serving families. Walk-ins welcome, no appointment needed.',
        phone: '+880 1888-111018',
        hours: '9 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400',
        externalBookingUrl: null,
        rating: 4.3,
        reviewCount: 423,
        popularity: 1800,
    },
    {
        name: 'Hair & Beyond',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Dhanmondi' },
        shortDescription: 'Premium hair extensions',
        description: 'Specialized in hair extensions, wigs, and advanced coloring techniques.',
        phone: '+880 1899-111019',
        hours: '11 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 734,
        popularity: 3000,
    },
    {
        name: 'Glamour Spa & Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'Luxury spa experience',
        description: 'Premium salon with full spa facilities. Massage, facials, body treatments available.',
        phone: '+880 1900-111020',
        hours: '10 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=400',
        externalBookingUrl: null,
        rating: 4.8,
        reviewCount: 1456,
        popularity: 4800,
    },
    // Adding more salons to reach 27
    {
        name: 'Attitude Men\'s Salon',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Banani' },
        shortDescription: 'Exclusively for men',
        description: 'Modern men\'s grooming parlor. Haircuts, shaves, beard styling, and facials.',
        phone: '+880 1911-111021',
        hours: '9 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400',
        externalBookingUrl: null,
        rating: 4.6,
        reviewCount: 645,
        popularity: 2700,
    },
    {
        name: 'Beauty Zone',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Uttara' },
        shortDescription: 'Complete beauty solutions',
        description: 'One-stop beauty center. Hair, skin, nails, and makeup services under one roof.',
        phone: '+880 1922-111022',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
        externalBookingUrl: null,
        rating: 4.5,
        reviewCount: 523,
        popularity: 2300,
    },
    {
        name: 'Chic Hair & Makeup Studio',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Bashundhara' },
        shortDescription: 'Party & bridal specialist',
        description: 'Expert in occasion makeup and hairstyling. Bridal packages with trial sessions.',
        phone: '+880 1933-111023',
        hours: '11 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 812,
        popularity: 3300,
    },
    {
        name: 'Trendy Cuts',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Mirpur' },
        shortDescription: 'Latest hairstyle trends',
        description: 'Young and vibrant salon. Always up-to-date with international hair trends.',
        phone: '+880 1944-111024',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.4,
        reviewCount: 421,
        popularity: 1900,
    },
    {
        name: 'Classic Barber House',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Dhanmondi' },
        shortDescription: 'Traditional barber shop',
        description: 'Old-school barber experience with modern standards. Razor shaves and classic cuts.',
        phone: '+880 1955-111025',
        hours: '9 AM - 8:30 PM',
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400',
        externalBookingUrl: null,
        rating: 4.6,
        reviewCount: 678,
        popularity: 2900,
    },
    {
        name: 'Hair Affair',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Gulshan' },
        shortDescription: 'Celebrity stylist salon',
        description: 'High-profile salon frequented by media personalities. Advanced color and styling.',
        phone: '+880 1966-111026',
        hours: '10 AM - 9 PM',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
        externalBookingUrl: null,
        rating: 4.9,
        reviewCount: 1678,
        popularity: 5600,
    },
    {
        name: 'The Salon & Spa',
        category: 'Haircut',
        location: { city: 'Dhaka', area: 'Banani' },
        shortDescription: 'Wellness & beauty center',
        description: 'Comprehensive wellness center with hair, spa, and aesthetic services.',
        phone: '+880 1977-111027',
        hours: '10 AM - 8 PM',
        imageUrl: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=400',
        externalBookingUrl: null,
        rating: 4.7,
        reviewCount: 923,
        popularity: 3700,
    },

    // Continue in next message due to length...
];

// Export for use in complete seed script
export default completeBusinessData;
